
export const GET_MEASUREMENTS_REQUEST = 'GET_MEASUREMENTS_REQUEST';
export const GET_MEASUREMENTS_SUCCESS = 'GET_MEASUREMENTS_SUCCESS';
export const GET_MEASUREMENTS_FAILURE = 'GET_MEASUREMENTS_FAILURE';