
export const GET_MEASUREMENTS_REQUEST = 'GET_MEASUREMENTS_REQUEST';
export const GET_MEASUREMENTS_SUCCESS = 'GET_MEASUREMENTS_SUCCESS';
export const GET_MEASUREMENTS_FAILURE = 'GET_MEASUREMENTS_FAILURE';


export const GET_MANDREKAS_REQUEST = 'GET_MANDREKAS_REQUEST';
export const GET_MANDREKAS_SUCCESS = 'GET_MANDREKAS_SUCCESS';
export const GET_MANDREKAS_FAILURE = 'GET_MANDREKAS_FAILURE';

export const GET_ARCELORMITTAL_REQUEST = 'GET_ARCELORMITTAL_REQUEST';
export const GET_ARCELORMITTAL_SUCCESS = 'GET_ARCELORMITTAL_SUCCESS';
export const GET_ARCELORMITTAL_FAILURE = 'GET_ARCELORMITTAL_FAILURE';